-- Profile fields for self-service user profile page
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'Lao PDR';
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS postal_code VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(500);
